version: '3.8'

services:

  mongodb:
    image: 'mongo'
    volumes:
      - data:/data/db  
    container_name: 'mongodb'  




  backend:
    image: 'goals-node'
    ports:
      - '80:80'

    volumes:
      - logs:/app/logs
      - /app/node_modules

    depends_on:
      - 'mongodb'  
      


  frontend:
    image: 'goals-react'

    ports:
        - '3000:3000'

    stdin_open: true

    tty: true   

    depends_on:
        - 'backend'     


volumes:
  data:
  logs:
